### ISSUE TITLE
Main Memory Unnecessarily Associated With Cores

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ut-parla/Parla.py#39]
Currently the devices for the individual CPU cores are each set up to have a dedicated piece of main memory that can be reserved by tasks. This may unnecessarily prevent tasks that need more memory from running at all. It'll likely take some refactoring in the scheduler to make this work right, but this limitation should be removed. This is not even remotely necessary for the upcoming deadline. I'm just documenting it for later.

**Comment by arthurp** [comment]
This only applies to the CPU device per core architecture. This is no longer the default. So this issue isn't a big deal. If we find that CPU device per core is useful, then we can look into this. It would be fairly complex though since resources are tied to devices in the design and this would require decoupling them. This would require changes to the device model *and* the scheduler itself.

**Comment by insertinterestingnamehere** [comment]
Yah, I'm inclined to call this resolved now that we switched the default in https://github.com/ut-parla/Parla.py/pull/45. I'll create a separate issue for allowing resources to exist independent of specific devices because that enables lots of different stuff.
