### ISSUE TITLE
Can't load MKL into a VEC

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ut-parla/Parla.py#9]
MKL doesn't load correctly into a VEC yet. All our current examples have had to run with OpenBLAS because of this. When we try to load MKL we get a dynamic linker error claiming that omp_num_threads can't be found, but it's not clear why there would be any problems with that.

**Comment by insertinterestingnamehere** [comment]
Note: anaconda has some special compatibility code for loading MKL. They ship it in a Python-level mkl package that their MKL-based numpy builds import first to get MKL loaded correctly. That's one likely point of failure that could cause an issue like this.

**Comment by arthurp** [comment]
The first place to look is in the `dlopen` wrapper for code inside VECs. It may be overriding or changing handling of the `GLOBAL` and `LOCAL` flags since those were broken in the unpatched glibc. Now that we use the patched glibc, it should work, but it's very possible that the wrapper still overrides the behavior since I may not have properly updated the wrapper and it might be overriding the `GLOBAL`/`LOCAL` flag in some way.

**Comment by insertinterestingnamehere** [comment]
Weirdly enough, this works now. If I install the latest version MKL via conda-forge it no longer uses the mkl-service package that had all that business with RTLD_GLOBAL. So MKL works now, but numba is broken by a similar issue. I'm closing this one. I'll file a separate issue to discuss.
